// <auto-generated />
namespace EcWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TipoContrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TipoContrato));
        
        string IMigrationMetadata.Id
        {
            get { return "201607022225529_TipoContrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
